### ISSUE TITLE
Calling websocket stuff

### ISSUE THREAD

**Issue by Zyles** [DennisSkoko/discord-bot#2]
Hi,

How would you implement something like this in your framework:

https://github.com/teamreflex/DiscordPHP/issues/133

Since it is not an event. The examples in DiscordPHP are put in basic.php file, but since you are abstracting stuff it should go somewhere else I assume.

Like they do here on the error:
https://github.com/teamreflex/DiscordPHP/blob/master/examples/basic.php

Your bot didn't have an errorhandler either so I am stumped on where to put this.

**Comment by DennisSkoko** [comment]
Hi

I think 'mention' is an event, it's just that is not an constant within `Discord\WebSockets\Event`.

This is one of the reasons I created this framework. So I could isolate every service in seperated classes. I would create a class that implements the `DS\Service`. Here is an example:

```php
<?php

use Discord\Parts\Channel\Message;
use DS\Service;

class Mention implements Service
{
    public function getEvent()
    {
        return "mention";
    }
    
    public function getListener()
    {
        return [$this, "respond"];
    }
    
    public function respond(Message $message)
    {
        $message->reply("Yes?");
    }
}
```

**Comment by Zyles** [comment]
Thank you this works. Weird design pattern choice from them to not have everything in the Event class if it is an event tho.
